apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "58.5.1"
dependencies:
  - name: kube-prometheus-stack
    version: 58.5.1
    repository: https://prometheus-community.github.io/helm-charts